name: Test package updates

on:
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      actions: read
    name: Update packages
    runs-on: windows-latest
    env:
      api_key: ${{ secrets.CHOCO_API }}
      gist_id: ${{ secrets.GIST_ID }}
      gist_id_test: ${{ secrets.GIST_TEST_ID }}
      github_user_repo: ${{ github.repository }}
      github_api_key: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache Choco lib
        uses: actions/cache@v3.2.2
        with:
         key: ${{ hashfiles('C:\ProgramData\chocolatey\lib') }}
         path: 'C:\ProgramData\chocolatey\lib'
      - name: Cache AU Instalation
        uses: actions/cache@v3.2.2
        with:
          key: ${{ hashfiles('C:\Program Files\WindowsPowerShell\Modules\AU') }}
          path: 'C:\Program Files\WindowsPowerShell\Modules\AU'

      - name: Chocolatey
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install au

      - name: Run test_all.ps1
        uses: Amadevus/pwsh-script@v2
        id: script
        with: 
          script: |
            $ErrorActionPreference = 'Continue'
            ./test_all.ps1
